commonConfig:
  databaseUser:
    valueFrom:
      secretKeyRef:
        name: coprocessor-user-rds-credentials
        key: username
  databasePassword:
    valueFrom:
      secretKeyRef:
        name: coprocessor-user-rds-credentials
        key: password
  databaseEndpoint:
    valueFrom:
      configMapKeyRef:
        name: coprocessor-config
        key: DATABASE_ENDPOINT
  databaseUrl: "postgresql://$(DATABASE_USER):$(DATABASE_PASSWORD)@$(DATABASE_ENDPOINT)/coprocessor"
  tracing:
    enabled: true
    endpoint: "http://observability-zws-testnet-observability-alloy.observability.svc.cluster.local:4317"

hostContractConfigMap:
  enabled: true
  name: eth-sc-addresses
  network: testnet

hostListenerShared:
  image:
    name: hub.zama.org/zama-protocol/zama-ai/fhevm/coprocessor/host-listener
    tag: v0.13.0
  replicas: 1
  args:
    serviceName: testnet-coprocessor-host-listener
  tracing:
    service: testnet-coprocessor-host-listener
  extraArgs:
    - --initial-block-time=12
    - --catchup-finalization-in-blocks=5
    - --dependence-cache-size=10000
    - --reorg-maximum-duration-in-blocks=50
    - --log-level=INFO
    - --dependence-cross-block
    - --dependent-ops-max-per-chain=0
  ports:
    metrics: "9100"
  serviceMonitor:
    enabled: true
  resources:
    requests:
      cpu: 1
      memory: 2Gi
    limits:
      cpu: 1
      memory: 2Gi
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: karpenter.sh/nodepool
                operator: In
                values:
                  - zws-pool
  tolerations:
    - key: karpenter.sh/nodepool
      effect: NoSchedule
      operator: Equal
      value: zws-pool
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

hostListenerPollerShared:
  image:
    name: hub.zama.org/zama-protocol/zama-ai/fhevm/coprocessor/host-listener
    tag: v0.13.0
  replicas: 1
  args:
    serviceName: testnet-coprocessor-host-listener-poller
  extraArgs:
    - --log-level=INFO
    - --dependence-cross-block
    - --finality-lag=15
  ports:
    metrics: "9100"
  serviceMonitor:
    enabled: true
  resources:
    requests:
      cpu: 1
      memory: 2Gi
    limits:
      cpu: 1
      memory: 2Gi
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: karpenter.sh/nodepool
                operator: In
                values:
                  - zws-pool
  tolerations:
    - key: karpenter.sh/nodepool
      effect: NoSchedule
      operator: Equal
      value: zws-pool
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

hostListenerCatchupOnlyShared:
  image:
    name: hub.zama.org/zama-protocol/zama-ai/fhevm/coprocessor/host-listener
    tag: v0.13.0
  replicas: 1
  args:
    serviceName: testnet-coprocessor-host-listener-catchup-only
  extraArgs:
    - --initial-block-time=12
    - --dependence-cache-size=10000
    - --reorg-maximum-duration-in-blocks=50
    - --catchup-finalization-in-blocks=5
    - --log-level=INFO
    - --dependence-cross-block
    - --only-catchup-loop
    - --start-at-block=-250
    - --end-at-block=-15
    - --catchup-loop-sleep-secs=60
  ports:
    metrics: "9100"
    healthcheck: "8080"
  serviceMonitor:
    enabled: true
  resources:
    requests:
      cpu: 1
      memory: 2Gi
    limits:
      cpu: 1
      memory: 2Gi
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: karpenter.sh/nodepool
                operator: In
                values:
                  - zws-pool
  tolerations:
    - key: karpenter.sh/nodepool
      effect: NoSchedule
      operator: Equal
      value: zws-pool
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

chains:
  - name: ethereum
    wsUrlValueFrom:
      secretKeyRef:
        name: rpc-credentials
        key: ethereum-rpc-ws-url
    httpUrlValueFrom:
      secretKeyRef:
        name: rpc-credentials
        key: ethereum-rpc-url
    aclContractAddressValueFrom:
      configMapKeyRef:
        name: eth-sc-addresses
        key: acl.address
    fhevmExecutorContractAddressValueFrom:
      configMapKeyRef:
        name: eth-sc-addresses
        key: fhevm_executor.address
    kmsGenerationContractAddressValueFrom:
      configMapKeyRef:
        name: eth-sc-addresses
        key: kms_generation.address
    hostListener:
      enabled: true
      useLegacyName: true
    hostListenerPoller:
      enabled: true
      useLegacyName: true
    hostListenerCatchupOnly:
      enabled: true
      useLegacyName: true

dbMigration:
  enabled: false
gwListener:
  enabled: false
tfheWorker:
  enabled: false
zkProofWorker:
  enabled: false
snsWorker:
  enabled: false
txSender:
  enabled: false