hostContractConfigMap:
  enabled: true
  name: eth-sc-addresses
  network: devnet
  addresses: {}

gatewayContractConfigMap:
  enabled: true
  name: gw-sc-addresses
  network: devnet
  addresses: {}

dbMigration:
  enabled: false

tfheWorker:
  enabled: false

zkProofWorker:
  enabled: false

snsWorker:
  enabled: false

gwListener:
  enabled: false

txSender:
  enabled: false
